---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: uninstall-application
  version: 0.1.0
  annotations:
    categories: Kubernetes
    vendor: LitmusChaos
spec:
  displayName: Uninstall Application
  categoryDescription: |
    Uninstall Application fault removes applications from the Kubernetes cluster after chaos testing.
    - Removes target applications (such as sock-shop) from the specified namespace.
    - Optionally deletes the namespace after removing resources.
    - Can be used as a post-chaos step to clean up the target application after running chaos experiments.
  keywords:
    - Kubernetes
    - Application Cleanup
    - Teardown
  platforms:
    - GKE
    - Konvoy
    - Packet(Kubeadm)
    - Minikube
    - EKS
    - AKS
    - Kind
    - Rancher
    - OpenShift(OKD)
  maintainers:
    - name: ksatchit
      email: karthik.s@harness.io
  experiments:
    - uninstall-application
  minKubeVersion: 1.12.0
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://litmuschaos.github.io/litmus/experiments/categories/contents
icon:
    - base64data: ""
      mediatype: ""